# Generated by Django 4.2.1 on 2023-06-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_details_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='UserDetail',
        ),
    ]
