# Generated by Django 4.2.1 on 2023-06-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_details',
            name='image',
            field=models.ImageField(default=2, upload_to='your_directory/'),
            preserve_default=False,
        ),
    ]
