# Generated by Django 4.2.1 on 2023-06-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_package_details_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_details',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
