# Generated by Django 4.2.1 on 2023-06-07 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_package_details_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package_details',
            name='image',
        ),
    ]
