# Generated by Django 4.2.1 on 2023-06-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_package_details_image_identifier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='package_details',
            name='image_identifier',
        ),
        migrations.AddField(
            model_name='package_details',
            name='photo',
            field=models.ImageField(default=2, upload_to='pics'),
            preserve_default=False,
        ),
    ]
