# Generated by Django 4.2.1 on 2023-06-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_image_remove_package_details_image_identifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='resturants_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('item_description', models.TextField(max_length=500)),
                ('items_price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
