# Generated by Django 4.2.1 on 2023-06-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_resturants_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grocery_name', models.CharField(max_length=200)),
                ('Grocery_price', models.IntegerField()),
                ('Grocery_description', models.TextField()),
                ('photo', models.ImageField(upload_to='photo')),
            ],
        ),
        migrations.DeleteModel(
            name='package_details',
        ),
    ]
