# Generated by Django 4.2.1 on 2023-06-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_grocery_details_delete_package_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicin_name', models.CharField(max_length=20)),
                ('Medicin_image', models.ImageField(upload_to='images')),
                ('Do_description', models.TextField(default='')),
                ('Medicin_price', models.IntegerField(default='')),
            ],
        ),
    ]
